 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dealersheps", type: :request do
  
  # Dealershep. As you add validations to Dealershep, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Dealershep.create! valid_attributes
      get dealersheps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dealershep = Dealershep.create! valid_attributes
      get dealershep_url(dealershep)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dealershep_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dealershep = Dealershep.create! valid_attributes
      get edit_dealershep_url(dealershep)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dealershep" do
        expect {
          post dealersheps_url, params: { dealershep: valid_attributes }
        }.to change(Dealershep, :count).by(1)
      end

      it "redirects to the created dealershep" do
        post dealersheps_url, params: { dealershep: valid_attributes }
        expect(response).to redirect_to(dealershep_url(Dealershep.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dealershep" do
        expect {
          post dealersheps_url, params: { dealershep: invalid_attributes }
        }.to change(Dealershep, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dealersheps_url, params: { dealershep: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dealershep" do
        dealershep = Dealershep.create! valid_attributes
        patch dealershep_url(dealershep), params: { dealershep: new_attributes }
        dealershep.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dealershep" do
        dealershep = Dealershep.create! valid_attributes
        patch dealershep_url(dealershep), params: { dealershep: new_attributes }
        dealershep.reload
        expect(response).to redirect_to(dealershep_url(dealershep))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dealershep = Dealershep.create! valid_attributes
        patch dealershep_url(dealershep), params: { dealershep: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dealershep" do
      dealershep = Dealershep.create! valid_attributes
      expect {
        delete dealershep_url(dealershep)
      }.to change(Dealershep, :count).by(-1)
    end

    it "redirects to the dealersheps list" do
      dealershep = Dealershep.create! valid_attributes
      delete dealershep_url(dealershep)
      expect(response).to redirect_to(dealersheps_url)
    end
  end
end
